#pragma config(Sensor, dgtl1,  enc1,           sensorQuadEncoder)
#pragma config(Motor,  port2,           sanic,         tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float deltaTime()
{
	float deltaT = time1[timer1];
	clearTimer(timer1);

	return deltaT;
}

int deltaAngularRotation() //Add option to read different encoders, then call for loop to cycle
{
	int deltaA = SensorValue[enc1];
	SensorValue[enc1] = 0;

	return deltaA;
}

double velocity() //Velocity in angles per
{
	return deltaAngularRotation()/deltaTime();
}
task main()
{
	while(true)
	{
		writeDebugStreamLine("DeltaA: %i", deltaAngularRotation());
		motor[sanic] = 127;
		wait1Msec(20);
	}
}
