#pragma config(Sensor, in8,    liftPot,        sensorPotentiometer)
#pragma config(Motor,  port1,           leftWinch,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightTopLift,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightBottomLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightClaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftTopLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightWinch,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Sensor, dgtl1,  enc1,           sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)


// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	motor[leftDrive]  = (vexRT[Ch1] + vexRT[Ch3]);  // (y + x)/2
		motor[rightDrive] = (vexRT[Ch1] - vexRT[Ch3]);  // (y - x)/2

	if(vexRT[Btn5D] == 1)      	//If button 5d is pressed...
		{
			motor[leftTopLift] = 127;
			motor[leftBottomLift] = 127;
			motor[rightTopLift] = 127;
			motor[rightBottomLift] = 127;
			//...raise the arm.
		}
		else if(vexRT[Btn5U] == 1)  	//Else, if button 5u is pressed...
		{
						motor[leftTopLift] = -127;
			motor[leftBottomLift] = -127;
			motor[rightTopLift] = -127;
			motor[rightBottomLift] = -127;  	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[leftTopLift] = -10;
			motor[leftBottomLift] = -10;
			motor[rightTopLift] = -10;
			motor[rightBottomLift] = -10;     	//...stop the arm.
		}
	if(vexRT[Btn6U] == 1)       	//If button 5U is pressed...
		{
			motor[rightClaw] = 127; //open claw
			motor[leftClaw] = 127;

		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[rightClaw] = -127;
			motor[leftClaw] = -127;  	//close claw
		}
		else if (vexRT [Btn7U] == 1)    //Else (neither button is pressed)...
		{
			motor[rightClaw] = 15;
			motor[leftClaw] = 15;
		}
		else
		{
			motor[rightClaw] = 0;
			motor[leftClaw] = 0;
		}

		if(vexRT[Btn8U] == 1) //If 8U pressed...
		{
			motor[leftWinch] = -127;
			motor[rightWinch] = -127;


			motor[leftBottomLift] = -127;	//Raise Lift
			motor[leftTopLift] = -127;
			motor[rightBottomLift] = -127;


			motor[rightTopLift] = -127;
		}
		else
  	if(vexRT[Btn8D] == 1) //If 8D pressed...
  	{
  		motor[leftWinch] = 127;
			motor[rightWinch] = 127;


			motor[leftBottomLift] = 127;	//Raise Lift
			motor[leftTopLift] = 127;
			motor[rightBottomLift] = 127;
			motor[rightTopLift] = 127;
  	}
  	else //If neither button pressed
  	{
  				motor[leftWinch] = 0;
					motor[rightWinch] = 0;//Set motor to 0
  	}



  	wait1Msec(8);
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
 }

//PID Code

 float Ks = .011811; //Scale factor for power to target speed conversion - see method powerToTargetSpeed
 float Kp = 1; //Constant for proportional portion of PID - rate of correction
 int refreshRate = 125; //Refresh rate in ms

int deltaAngularRotation() //Add option to read different encoders, then call for loop to cycle
{
 	int deltaA = SensorValue[enc1];

 	return deltaA;
 }

 float deltaTime()
 {
 	float deltaT = time1[timer1];

 	if(deltaT == 0) //For first execution where deltaT is 0
 		return refreshRate; //Set this equal to refresh time
 	return deltaT;
 }

 float velocity() //Velocity in angles per refreshRate ms - may need to increase time interval to be more accurate
 {
 		return((float)deltaAngularRotation())/deltaTime();
 }

 float powerToTargetSpeed(int power) //Calculate the target speed based on the set power
 {
 	return (float)power*Ks; //Constant converts power to angles per ms
 }

 int speedToPower(float speed)
 {
 	return (int)(speed/Ks); // Reverse conversion from powerToTargetSpeed
 }

 int correctedPIDPowerLevel(int powerLevel, float currentvelocity)  //Returns the value the motor power must be changed by to achieve PIDdiness
 {
 	float targetSpeed = powerToTargetSpeed(powerLevel);
 	//float actualSpeed = velocity();

 	return speedToPower(targetSpeed-currentvelocity);

 }

 task main()
 {
  int motorvalue = testMotorPower;
 	while(true)
 	{

 	float veloocity = velocity();

		writeDebugStreamLine("Original Power Level: %d",(testMotorPower));
		writeDebugStreamLine("Actual Velocity: %.4f", veloocity);
		writeDebugStreamLine("Calculated Target Velocity: %.4f", powerToTargetSpeed(testMotorPower));
		writeDebugStreamLine("PID correctedPIDPowerLevel: %d", motorvalue);



		writeDebugStreamLine("");
		motorvalue = motorvalue+correctedPIDPowerLevel(motorvalue, veloocity)*Kp;
		if(motorvalue < -127)
			motorvalue = -127;
		if(motorvalue > 127)
			motorvalue = 127;
 		motor[sanic] = motorvalue;

 		SensorValue[enc1] = 0; //Clear encoder and timer
 		clearTimer(timer1);
 		wait1Msec(refreshRate);
	}
}
