#pragma config(Sensor, dgtl7,  enc1,           sensorQuadEncoder)
#pragma config(Motor,  port7,           sanic,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 float Ks = .011811; //Scale factor for power to target speed conversion - see method powerToTargetSpeed
 float Kp = 1; //Constant for proportional portion of PID - rate of correction
 int refreshRate = 125; //Refresh rate in ms

 int testMotorPower = 127; //Enter test motor speed

int deltaAngularRotation() //Add option to read different encoders, then call for loop to cycle
{
 	int deltaA = SensorValue[enc1];

 	return deltaA;
 }

 float deltaTime()
 {
 	float deltaT = time1[timer1];

 	if(deltaT == 0) //For first execution where deltaT is 0
 		return refreshRate; //Set this equal to refresh time
 	return deltaT;
 }

 float velocity() //Velocity in angles per refreshRate ms - may need to increase time interval to be more accurate
 {
 		return((float)deltaAngularRotation())/deltaTime();
 }

 float powerToTargetSpeed(int power) //Calculate the target speed based on the set power
 {
 	return (float)power*Ks; //Constant converts power to angles per ms
 }

 int speedToPower(float speed)
 {
 	return (int)(speed/Ks); // Reverse conversion from powerToTargetSpeed
 }

 int correctedPIDPowerLevel(int powerLevel, float currentvelocity)  //Returns the value the motor power must be changed by to achieve PIDdiness
 {
 	float targetSpeed = powerToTargetSpeed(powerLevel);
 	//float actualSpeed = velocity();

 	return speedToPower(targetSpeed-currentvelocity);

 }

 task main()
 {
  int motorvalue = testMotorPower;
 	while(true)
 	{

 	float veloocity = velocity();

		writeDebugStreamLine("Original Power Level: %d",(testMotorPower));
		writeDebugStreamLine("Actual Velocity: %.4f", veloocity);
		writeDebugStreamLine("Calculated Target Velocity: %.4f", powerToTargetSpeed(testMotorPower));
		writeDebugStreamLine("PID correctedPIDPowerLevel: %d", motorvalue);



		writeDebugStreamLine("");
		motorvalue = motorvalue+correctedPIDPowerLevel(motorvalue, veloocity)*Kp;
		if(motorvalue < -127)
			motorvalue = -127;
		if(motorvalue > 127)
			motorvalue = 127;
 		motor[sanic] = motorvalue;

 		SensorValue[enc1] = 0; //Clear encoder and timer
 		clearTimer(timer1);
 		wait1Msec(refreshRate);
	}
}
