#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Motor,  port1,           leftH,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBottomLift, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightClaw,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rightTopLift,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftTopLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightH,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)


// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	int h;
  while (true)
  {
  	h = vexRT[Ch4];

  	if(abs(h) < 30)
  		h = 0;
  	motor[leftH] = h;
		motor[rightH] = h;

  	motor[leftDrive]  = (int)((float)(vexRT[Ch1] + vexRT[Ch3])*0.6);  // (y + x)/2
		motor[rightDrive] = (vexRT[Ch1] - vexRT[Ch3]);  // (y - x)/2

	if(vexRT[Btn5D] == 1)      	//If button 5d is pressed...
		{
			motor[leftTopLift] = 127;
			motor[leftBottomLift] = 127;
			motor[rightTopLift] = 127;
			motor[rightBottomLift] = 127;
			//...raise the arm.
		}
		else if(vexRT[Btn5U] == 1)  	//Else, if button 5u is pressed...
		{
			motor[leftTopLift] = -127;
			motor[leftBottomLift] = -127;
			motor[rightTopLift] = -127;
			motor[rightBottomLift] = -127;  	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[leftTopLift] = -10;
			motor[leftBottomLift] = -10;
			motor[rightTopLift] = -10;
			motor[rightBottomLift] = -10;     	//...stop the arm.
		}
	if(vexRT[Btn6U] == 1)       	//If button 5U is pressed...
		{
			motor[rightClaw] = 127; //open claw
			motor[leftClaw] = 127;

		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[rightClaw] = -127;
			motor[leftClaw] = -127;  	//close claw
		}
		else if (vexRT [Btn7U] == 1)    //Else (neither button is pressed)...
		{
			motor[rightClaw] = 15;
			motor[leftClaw] = 15;
		}
		else
		{
			motor[rightClaw] = 0;
			motor[leftClaw] = 0;
		}



  	wait1Msec(20);
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
 }
