#pragma config(Motor,  port2,           frontLeft,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           backRight,     tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void updateDrive()
{
	int rightPower = (vexRT[Ch3]-vexRT[Ch1]);
	int leftPower = (vexRT[Ch3]+vexRT[Ch1]);

	motor[frontLeft] = leftPower;
	motor[frontRight] = rightPower;
	motor[backLeft] = leftPower;
	motor[backRight] = rightPower;

}

task main()
{
	while(true)
	{
		updateDrive();
		wait1Msec(8);
	}

}
