#pragma config(Motor,  port2,           leftFront,     tmotorNone, openLoop)
#pragma config(Motor,  port3,           rightFront,    tmotorNone, openLoop)
#pragma config(Motor,  port5,           leftBack,      tmotorNone, openLoop)
#pragma config(Motor,  port6,           rightBack,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int x = vexRT[Ch4];
int y = vexRT[Ch3];
int r = vexRT[Ch1];

void xDrive()
{
	motor[leftFront] = x + y + r;
	motor[rightFront] = x - y + r;
	motor[leftBack] = -x - y + r;
	motor[rightBack] = -x + y + r;
}

task main()
{
	while(true)
	{
		xDrive();
		wait1Msec(20);
	}
}
